### ISSUE TITLE
Should we have some sort of code style?

### ISSUE THREAD

**Issue by schneiderfelipe** [cclib/cclib#1122]
I notice there's not much consistency across the codebase in some cases (e.g., `'strings'` and `"strings"`, etc.). **Any** code style is good enough (I really like [black](https://github.com/psf/black)). This could be enforced in a post-commit or post-merge hook.

**Comment by arosen93** [comment]
I also would love to see `black .` applied to the repo, but I will `black` just about anything...

**Comment by mscho527** [comment]
I think people were asked to run `black -l 100` on any file they changed in the commit. As far as I remember, there was a discussion on whether we want to run `black` on the entire repo some time ago, but we decided not to because it would make it harder to track changes through git history. Please correct me if I am not recalling the discussion correctly!

**Comment by berquist** [comment]
> I think people were asked to run `black -l 100` on any file they changed in the commit. As far as I remember, there was a discussion on whether we want to run `black` on the entire repo some time ago, but we decided not to because it would make it harder to track changes through git history. Please correct me if I am not recalling the discussion correctly!

This is correct on all points. I'm not sure it would be as bad as some renames or moves: I needed multiple revision checkouts to see the original history of `io`.

One more concrete (and common) concern is that it will mess with all open PRs, so we should try and push them through before running a formatter. Rebasing them after formatting the codebase will be a pain.

I use black as part of https://pre-commit.com/ (but not in GHA) for all my other projects. I think we should do whatever makes contributing to the code and modifying it easier.

**Comment by shivupa** [comment]
What Minsik said was indeed true. I have some new thoughts about this.

I agree with making it easier to contribute. Personally I think precommit hooks are a little tedious on developers since it requires them to set it up, but I am open to discussion on that point.

I do think just running `black -l 100` on the source and adding a [github action](https://black.readthedocs.io/en/stable/integrations/github_actions.html) to check if future contributions abide by the constraints sounds like a good option.

**Comment by berquist** [comment]
I agree with not requiring pre-commit hooks, at least to start off with; I usually just leave the hook uninstalled and call `pre-commit run -a` occasionally which runs black/linters/mypy/... with the specification preconfigured in a file (`.pre-commit-config.yaml`) so I don't need to remember the exact command to run for each tool:

``` yaml
---
fail_fast: true
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/PyCQA/isort
    rev: "5.10.1"
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: "22.8.0"
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/pylint
    rev: "v2.15.3"
    hooks:
      - id: pylint
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.981"
    hooks:
      - id: mypy
        additional_dependencies:
          - attrs
          - types-pyyaml
        args: []
```
and then the rest of the configuration is in `pyproject.toml`.

Regarding the history/blame issue, I recently tried the approach at https://akrabat.com/ignoring-revisions-with-git-blame/ and it works, though it'd be nice if it was automated.

Since we're making a concerted effort to clean up outstanding PRs, this will be one of the first things we do after that.
